### ISSUE TITLE
請問大大能否更新0.5.9版本 

### ISSUE THREAD

**Issue by cookier0218** [ififi2017/Hackintosh-MSI-MPG-Z390-GAMING-PLUS#1]
不好意思, 因為一直裝不成功,
又還不太理解錯誤在哪？
不知道會不會是0.5.8版本的因素
所以想請問大大有否更新0.5.9

anyway謝謝你的分享

**Comment by ififi2017** [comment]
目前此版本仅支持macOS 10.15.4，如果是macOS 10.15.5的话安装会不成功。因为这套配置是我朋友的，所以需要远程配置。如果顺利的话我会在近几天内更新。感谢反馈。

**Comment by ififi2017** [comment]
刚才已经做好了一个Alpha版本但是没有实机测试，如果方便请帮我测试一下。谢谢。
[2.0 Alpha](https://github.com/ififi2017/Hackintosh-MSI-MPG-Z390-GAMING-PLUS/releases/tag/v2.0-alpha)

**Comment by cookier0218** [comment]
仍然失敗, 但由於我都沒成功, 所以也可能我自己bios設定錯誤

說明一下我的安裝過程
1. 利用司波图的安裝包 创建U盘 選擇1O , y , MAC15.5路徑創建U盤
2. copy 2.0Aplha下的ACPI,Drives , Kext, config.plist等檔案到U盤相對應位置
3. 利用司波图的安裝包 下的ProperTree編輯config.plist
    *ctrl+shift+r 設定OC關聯性
    * 設定自己的MLB , Serial, UUID等資訊 

4, 重啟看不到OPENCORE的選單, 如連結 https://d.pr/i/vyt6c0

我的BIOS設定
cfg lock 設定Disable
VT-D   設定Disable
MSI Fast Boot 及Fast boot 設定Disable

CSM 找不到選項可以關閉

Above 4G Memory/Crypto Currency mining  設定ENABLE  <~~自以為他是司波图說的Above 4Gdecoding, 不確定對否
ErP Ready 設定enable
XHCI Hand-off 設定enable
Legacy USB Support 設定enable
Virtualization 設定enable

**Comment by ififi2017** [comment]
看您的BIOS描述应该是没有问题的，图片上的错误信息显示是OpenCore的config文件的问题，今晚我会和朋友远程完善该版本。如果他那边可以正常使用的话会发布一个正式版。到时再来检查您的电脑是哪里出了问题。

**Comment by cookier0218** [comment]
剛剛先依照大大說的 用原來大大0.5.8這版本灌15.4 
有到了安裝畫面, 格式化硬碟成apfs後進行安裝，
似乎安裝完後重開機, 選擇macOS internal 後就變黑畫面
不知大大有沒有經驗可能錯在哪？
會是opencore關於顯卡的設置那邊嗎？可為何又能進去安裝介面https://d.pr/i/Fn2cab

目前顯卡是用集顯
獨顯rx580滿血的剛好送技嘉原廠修理, 等它回來, 可以直接插 用獨顯輸出嗎

**Comment by ififi2017** [comment]
你好，因为最近工作比较繁忙所以忘记回复了。另请问您使用的主板上的视频接口是DVI接口还是HDMI呢？

**Comment by cookier0218** [comment]
兩個都嘗試了, 狀況一樣; 

昨天2020.0703滿血的RX580修回來了

昨天依照opencore官網, 將所有SSDT編譯一次（發現0.5.9跟0.5.8不一樣<~~可能是關鍵）, 
接著按官網教學設定走一遍, 最後加上大大原本config.plist裡的ALC892 Device設定, 
現在已經安裝成功, 

RX580 DP加上集顯加速解碼. https://d.pr/i/bbVJOw
音效成功、ＵＳＢ均可正常使用
外加上trackpad的kext(尚未測試過)

我的BIOS設定

cfg lock 設定Disable
VT-D 設定Disable
MSI Fast Boot 及Fast boot 設定Disable

（獨顯＋集顯）設定PEG、６４mb、enable
Above 4G Memory/Crypto Currency mining 設定ENABLE
ErP Ready 設定enable
XHCI Hand-off 設定enable
Legacy USB Support 設定enable
Virtualization 設定enable

這是我的EFI 亦分享給大大（已改過MLB、序號）
https://d.pr/f/77GhPS

最後沒你的協助, 差點撐不下去, 幫助很大, 非常謝謝大大,

**Comment by ififi2017** [comment]
嗯，解决了就好，主要我这边也没有测试机器所以做起来很麻烦。
